# Generated by Django 3.1.4 on 2020-12-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_fieldcode', models.CharField(max_length=50)),
                ('project_fieldname', models.CharField(max_length=50)),
                ('project_introduction', models.CharField(max_length=2000)),
                ('project_code', models.CharField(max_length=50)),
                ('project_photo', models.CharField(max_length=255)),
                ('project_status', models.CharField(max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.CharField(max_length=50)),
                ('update_user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
